# Generated by Django 5.0.6 on 2024-08-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_rename_hour_worktype_hours_remove_worktype_traktor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[(1, 'Ожидание'), (2, 'Успешно'), (-1, 'Отменен'), (-2, 'Отменен после завершения')], default=1, max_length=255)),
                ('type', models.CharField(choices=[('cash', 'Наличие'), ('card', 'Онлайн')], default='card', max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='blog.order')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'finance_transactions',
                'default_related_name': 'transactions',
                'unique_together': {('order',)},
            },
        ),
        migrations.CreateModel(
            name='TransactionPayme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(editable=False, max_length=255)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('state', models.CharField(choices=[(1, 'Ожидание'), (2, 'Успешно'), (-1, 'Отменен'), (-2, 'Отменен после завершения')], default=1, max_length=255)),
                ('last_method', models.CharField(max_length=255)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Транзакция Payme',
                'verbose_name_plural': 'Транзакции Payme',
                'db_table': 'finance_transaction_payme',
            },
        ),
    ]
