# Generated by Django 5.0.6 on 2024-05-16 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "Место", "verbose_name_plural": "Места"},
        ),
        migrations.AlterModelOptions(
            name="fertiliser",
            options={"verbose_name": "Удобрение", "verbose_name_plural": "Удобрения"},
        ),
        migrations.AlterModelOptions(
            name="seed",
            options={"verbose_name": "Семя", "verbose_name_plural": "Семена"},
        ),
        migrations.AlterModelOptions(
            name="tractor",
            options={"verbose_name": "Трактор", "verbose_name_plural": "Тракторы"},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "Работник", "verbose_name_plural": "Работники"},
        ),
        migrations.AlterModelTable(
            name="area",
            table=None,
        ),
        migrations.AlterModelTable(
            name="fertiliser",
            table=None,
        ),
        migrations.AlterModelTable(
            name="seed",
            table=None,
        ),
        migrations.AlterModelTable(
            name="tractor",
            table=None,
        ),
        migrations.AlterModelTable(
            name="worker",
            table=None,
        ),
    ]
