# Generated by Django 5.0.6 on 2024-06-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("coefficient", models.FloatField()),
                ("monthly_wage", models.IntegerField()),
                ("daily_wage", models.FloatField()),
                ("weekly_wage", models.FloatField()),
                ("wage_with_coefficient", models.IntegerField()),
                ("wage_for_7_hours", models.FloatField()),
            ],
            options={
                "verbose_name": "Тариф работника",
                "verbose_name_plural": "Тарифы работников",
                "db_table": "worker_tariffs",
            },
        ),
        migrations.RenameModel(
            old_name="Tariff",
            new_name="TractorTariff",
        ),
        migrations.AlterModelOptions(
            name="tractortariff",
            options={
                "verbose_name": "Тариф трактора",
                "verbose_name_plural": "Тарифы тракторов",
            },
        ),
        migrations.RemoveField(
            model_name="tractor",
            name="tariff",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="tariff",
        ),
        migrations.AddField(
            model_name="tractor",
            name="tariffs",
            field=models.ManyToManyField(to="blog.tractortariff"),
        ),
        migrations.AlterModelTable(
            name="tractortariff",
            table="tractor_tariffs",
        ),
        migrations.AddField(
            model_name="worker",
            name="tariffs",
            field=models.ManyToManyField(to="blog.workertariff"),
        ),
    ]
