# Generated by Django 5.0.6 on 2024-06-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_workertariff_rename_tariff_tractortariff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TractorTariffAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.IntegerField()),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.tractortariff",
                    ),
                ),
                (
                    "tractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.tractor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение тарифа трактора",
                "verbose_name_plural": "Назначения тарифов тракторов",
                "db_table": "tractor_tariff_assignments",
            },
        ),
        migrations.CreateModel(
            name="WorkerTariffAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.IntegerField()),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.workertariff",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.worker"
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение тарифа работника",
                "verbose_name_plural": "Назначения тарифов работников",
                "db_table": "worker_tariff_assignments",
            },
        ),
    ]
