# Generated by Django 5.0.6 on 2024-06-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_area_options_alter_fertiliser_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="mems_images/")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Мем",
                "verbose_name_plural": "Мемы",
            },
        ),
    ]
