# Generated by Django 5.0.6 on 2024-06-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_tractortariffassignment_workertariffassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktype",
            name="traktor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.tractor",
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.worker",
            ),
        ),
    ]
