# Generated by Django 5.0.6 on 2024-06-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_worktype_traktor_alter_worktype_worker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worktype",
            old_name="hour",
            new_name="hours",
        ),
        migrations.RemoveField(
            model_name="worktype",
            name="traktor",
        ),
        migrations.RemoveField(
            model_name="worktype",
            name="worker",
        ),
        migrations.AddField(
            model_name="worktype",
            name="tractor_tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.tractortariff",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="worker_tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.workertariff",
            ),
        ),
    ]
