# Generated by Django 5.0.6 on 2024-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_hour_worktype_hours_remove_worktype_traktor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, verbose_name='Номер карты для оплаты')),
                ('is_active', models.BooleanField(default=False, unique=True, verbose_name='Активная')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pwd',
            field=models.CharField(max_length=10, null=True, verbose_name='Пароль покупки'),
        ),
    ]
